### ISSUE TITLE
No module named render and loss.

### ISSUE THREAD

**Issue by LaFeuilleMorte** [SanketDhuri/crm_3d_training#2]
Hi, thanks for sharing the train code. But however I cannot manage to make it work. As these two modules are not found: render and loss. (I suppose it's not a third-party lib and there might be some scripts missing in the repo)

**Comment by SanketDhuri** [comment]
Hi @LaFeuilleMorte, I appreciate you bringing this to my attention. You’re correct; the render and loss modules were missing. I’ve now included the render.py file and the SDF loss function in the notebook. Please try running the code again, and let me know if you encounter any further issues.  Thank you!
